### ISSUE TITLE
ipfs for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-ipfs#1]
## Description

The InterPlanetary File System (IPFS) is a content-based addressing, versioning, peer-to-peer hypermedia transfer protocol that combines P2P network technology, BitTorrent transfer technology, Git version control, self-proving file systems, and other technologies, and is a new generation of HTTP-based This project will implement the go This project will implement the go-storage Storager interface for IPFS, enabling users to manipulate data on ipfs nodes through a unified interface.

## Roadmap

- [x] Choose a well maintained IPFS library
- [x] https://github.com/beyondstorage/go-service-ipfs/pull/3
  - [x] Implement all interface that Storager required
  - [x] Setup integration tests
- [x] Add docs in [site](https://github.com/aos-dev/site)
- [x] Add examples in [example](https://github.com/aos-dev/go-storage-example)

[go-storage]: https://github.com/aos-dev/go-storage

**Comment by zu1k** [comment]
Is this issue ready to be closed?
@Prnyself @Xuanwo

**Comment by Xuanwo** [comment]
> Is this issue ready to be closed?

I think all work that tracks in this issue has been done, let's close it! Thank you for your work!
